let data = [];

data[0] = [
  '<center> <img src="images/ainsley.png"> <p> <h2> @YourBoiAinsleyy </h2> </br> <br> <video width="300" height="165" controls> <source src="videos/ainsleyjerkchicken.mov" type="video/mp4"> </video> </br> </p> </center>',
  '<center> <img src="images/ainsley.png"> <p> <h2> @YourBoiAinsleyy </h2> </br> <br> <h3> Crispy! </br> <p> <h6> #crispy #celebritychef #cooking </h6> </h3> </p> <p> </br> </p> </center>',
  '<center> <img src="images/ainsley.png"> <p> <h2> @YourBoiAinsleyy </h2> </br> <h3> Hehe boi! A very nice site! </br> <h6> #heheboi #ainsley </h6> </h3> </br> </p> </center>',
  '<center> <img src="images/gregsdad.png"> <p> <h2> @FrankHeffleyyyy </h2> </br> <br> <h3> Just going off to a bathroom that actually has A LOCK ON IT! </br> <h6> #toilethumour #bathroom </h6> </h3> </br> </p> </center>',
  "<center> <img src='images/gregsdad.png'> <p> <h2> @FrankHeffleyyyy </h2> </br> <br> <h3> I'M THE LAUGHER! I'M THE LAUGHINGEST LAUGHER THAT EVER LAUGHED! HAHAHAHAHAAAA! </br> <h6> #hahaha #funny #meme </h6> </h3> </br> </p> </center>",
  '<center> <img src="images/gregsdad.png"> <p> <h2> @FrankHeffleyyyy </h2> </br> <br> <h3> Someone stole my figurines! How many times do I have to tell them - they are NOT TOYS! THEY ARE FIGURINES! </br> <h6> #robbery #news #figurines </h6> </h3> </br> </p> </center>',
  '<center> <img src="images/wonka.png"> <p> <h2> @RealWonka </h2> </br> <br> <h3> THE MANAGER GETS NOTHING! YOU LOSE! GOOD DAY SIR! </br> <h6> #youlose #nothing #wonka </h6> </h3> </br> </p> </center>',
  '<center> <img src="images/wonka.png"> <p> <h2> @RealWonka </h2> </br> <br> <h3> Sorry but any questions to me must be submitted in comment. </br> <h6> #questions #iconic </h6> </h3> </br> </p> </center>',
  "<center> <img src='images/wonka.png'> <p> <h2> @RealWonka </h2> </br> <br> <h3> This site is certainly the sailor's way...according to that manager... </br> <h6> #managerhate #infinite </h6> </br> </p> </h3> </center>",
  '<center> <img src="images/michael.png"> <p> <h2> @NoiceMichaelRosen </h2> </br> <br> <h3> MMMMMM! I LOVE CHOCOLATE CAKE! </br> <h6> #chocolatecake #food #yummy </h6> </br> </h3> </center>',
  '<center> <img src="images/michael.png"> <p> <h2> @NoiceMichaelRosen </h2> </br> <br> <video width="300" height="165" controls> <source src="videos/nobreathing.mp4" type="video/mp4"> </video> </br> </p> </center>',
  '<center> <img src="images/michael.png"> <p> <h2> @NoiceMichaelRosen </h2> </br> <br> <h3> Just looked at this site! NOICE! </br> <h6> #noice #recommended </h6> </h3> </br> </center>',
  '<center> <img src="images/einstein.png"> <p> <h2> @Einstein55 </h2> </br> <br> <h3> Science has changed a lot since my death... </br> <h6> #science #physics #modern </h6> </h3> </br> </p> </center>',
  '<center> <img src="images/einstein.png"> <p> <h2> @Einstein55 </h2> </br> <br> <h3> Remember that formula E=MC squared! </br> <h6> #spicy #formula </h6> </h3> </br> </p> </center>',
  '<center> <img src="images/einstein.png"> <p> <h2> @Einstein55 </h2> </br> <br> <h3> My famous tongue became famous for what... </br> <h6> #meme #famousphoto </h6> </h3> </br> </p> </center>',
  "<center> <img src='images/grunty.png'> <p> <h2> @GruntildaWinkybunion93 </h2> </br> <br> <h3> Manager must stop, Grunty says, or your stupid site I'll erase! </br> <h6> #managerhate #grunty #rhyming </h6> </h3> </br> </p> </center>",
  '<center> <img src="images/grunty.png"> <p> <h2> @GruntildaWinkybunion93 </h2> </br> <br> <video width="300" height="165" controls> <source src="videos/gruntyfortnite.mp4" type="video/mp4"> </br> </p> </center>',
  '<center> <img src="images/grunty.png"> <p> <h2> @GruntildaWinkybunion93 </h2> </br> <br> <h3> Trying to find the end is so painfully unfair, there are so many better sites down at my lair! </br> <h6> #infinity #grunty #stupid </h6> </h3> </br> </p> </center>',
  "<center> <img src='images/johnny.png'> <p> <h2> @MrJackTorrance </h2> </br> <br> <h3> HERE'S JOHNNY! </br> <h6> #theshining #iconicquotes </h6> </h3> </br> </p> </center>",
  "<center> <img src='images/johnny.png'> <p> <h2> @MrJackTorrance </h2> </br> <br> <h3> Thank you to Disney for using my iconic scene! </br> <h6> #disney #findingnemo #heresbrucie </h6> </h3> </br> </p> </center>",
  '<center> <img src="images/johnny.png"> <p> <h2> @MrJackTorrance </h2> </br> <br> <h3> Wendy is lost somewhere out there... </br> <h6> #whereswendy #jacktorrance </h6> </h3> </br> </p> </center>',
  '<center> <img src="images/leonidas.png"> <p> <h2> @Leonidas300 </h2> </br> <br> <h3> TONIGHT WE DINE IN HELL! </br> <h6> #300 #quotes #motivation </h6> </h3> </br> </p> </center>',
  '<center> <img src="images/leonidas.png"> <p> <h2> @Leonidas300 </h2> </br> <br> <h3> madness...THIS...IS...SPARTAAAAAAA!! </br> <h6> #spartaaaaaa #300 </h6> </h3> </br> </p> </center>',
  '<center> <img src="images/leonidas.png"> <p> <h2> @Leonidas300 </h2> </br> <br> <video width="300" height="165" controls> <source src="videos/thisissparta.mov" type="video/mp4"> </video> </br> </p> </center>',
  '<center> <img src="images/monkey.png"> <p> <h2> @MonkeyBoyyyy </h2> </br> <br> <h3> Some idiot from the zoo staff just shipped my brother off to Brazil! WHY?! </br> <h6> #monkeynews #animals </h6> </h3> </br> </p> </center>',
  '<center> <img src="images/monkey.png"> <p> <h2> @MonkeyBoyyyy </h2> </br> <br> <h3> Will you marry me? </br> <h6> #monkeyspeak #english </h6> </h3> </br> </p> </center>',
  '<center> <img src="images/monkey.png"> <p> <h2> @MonkeyBoyyyy </h2> </br> <br> <h3> OOO OOO OOO OOO OOO OOO OOO OOO OOO! </br> <h6> #monkeylanguage #ooo </h6> </h3> </br> </p> </center>',
  "<center> <img src='images/mrbean.png'> <p> <h2> @TheRealMrBean </h2> </br> <br> <h3> Um...hello? I'm Bean. Mr. Bean. Hehehehe. </br> <h6> #mrbean #hello </h6> </h3> </br> </p> </center>",
  "<center> <img src='images/mrbean.png'> <p> <h2> @TheRealMrBean </h2> </br> <br> <video width='300' height='165' controls> <source src='videos/handybean.mp4' type='video/mp4'> </video> </br> </p> </center>",
  '<center> <img src="images/mrbean.png"> <p> <h2> @TheRealMrBean </h2> </br> <br> <h3> Mrs. Wicket kicked me out...ugh... </br> <h6> #landlady #why </h6> </h3> </br> </p> </center>',
  '<center> <img src="images/scrooge.png"> <p> <h2> @ScroogeRulez </h2> </br> <br> <h3> Bah...humbug... </br> <h6> #charlesdickens #achristmascarol </h6> </h3> </br> </p> </center>',
  "<center> <img src='images/scrooge.png'> <p> <h2> @ScroogeRulez </h2> </br> <br> <h3> The manager's money should belong to me. </br> <h6> #managerhate #money #gimme </h6> </h3> </br> </p> </center>",
  '<center> <img src="images/scrooge.png"> <p> <h2> @ScroogeRulez </h2> </br> <br> <h3> Grrr! Hope this manager has a MISERABLE CHRISTMAS! </br> <h6> #managerhate #ihateyou </h6> </h3> </br> </p> </center>',
  '<center> <img src="images/shrek.png"> <p> <h2> @ShrekFromTheSwamp </h2> </br> <br> <h3> WHAT IS THE MANAGER DOING IN MY SWAMP?! </br> <h6> #managerhate #swamp </h6> </h3> </br> </p> </center>',
  '<center> <img src="images/shrek.png"> <p> <h2> @ShrekFromTheSwamp </h2> </br> <br> <video width="300" height="165" controls> <source src="videos/shrekkaraoke.mp4" type="video/mp4"> </video> </br> </p> </center>',
  '<center> <img src="images/shrek.png"> <p> <h2> @ShrekFromTheSwamp </h2> </br> <br> <h3> Manager? This is the part where you run away... </br> <h6> #stayout #managerhate </h6> </h3> </br> </p> </center>',
  "<center> <img src='images/sid.png'> <p> <h2> @SidPhillips999 </h2> </br> <br> <h3> DOCTOR YOU DONE IT! </br> <h6> #bwahahaha #doctor </h6> </h3> </br> </p> </center>",
  '<center> <img src="images/sid.png"> <p> <h2> @SidPhillips999 </h2> </br> <br> <h3> MANAGER, WHERE ARE YOUR REBEL FRIENDS NOW?! </br> <h6> #torture #rebel </h6> </h3> </br> </p> </center>',
  '<center> <img src="images/sid.png"> <p> <h2> @SidPhillips999 </h2> </br> <br> <h3> We have ways of making you toys talk...or even a certain manager! </br> <h6> #talkingtoys </h6> </h3> </br> </center>',
  '<center> <img src="images/successkid.png"> <p> <h2> @RealSuccessKid </h2> </br> <br> <h3> Gonna set out and BEAT THAT MANAGER! </br> <h6> #successkid #determination </h6> </h3> </br> </p> </center>',
  '<center> <img src="images/successkid.png"> <p> <h2> @RealSuccessKid </h2> </br> <br> <h3> YES! My favourite show starts in 10 minutes! </br> <h6> #television #waitisover </h6> </h3> </br> </p> </center>',
  '<center> <img src="images/successkid.png"> <p> <h2> @RealSuccessKid </h2> </br> <br> <h3> Just figured out the C++ script! YES! </br> <h6> #c++ #ihatethatcode #doneit </h6> </h3> </br> </p> </center>',
  '<center> <img src="images/unavailable.png"> <p> <h2> @SITE.ERROR.TEAM </h2> </br> <br> <h3> Post is unavailable to view. </br> Please check back later. </h3> </br> </p> </center>',
  '<center> <img src="images/wallace.png"> <p> <h2> @ThatInventorWallace </h2> </br> <br> <h3> I  like cheese. </br> <h6> #cheesegromit #food </h6> </h3> </br> </p> </center>',
  '<center> <img src="images/wallace.png"> <p> <h2> @ThatInventorWallace </h2> </br> <br> <h3> HELP! That stupid manager just nicked me cheese! STOP HIM GROMIT! </br> <h6> #sheeprustle #robbery #news </h6> </h3> </br> </p> </center>',
  "<center> <img src='images/wallace.png'> <p> <h2> @ThatInventorWallace </h2> </br> <br> <h3> I guess the cheese inspired my wide smile I'm notably known for. </br> <h6> #smile #cheese </h6> </h3> </br> </p> </center>",

  '<center> <img src="images/azaraskin.png"> <p> <h2> @AzaRaskinOG </h2> </br> <br> <h3> Once I find that manager, he is out of a job immediately! This is NOT what I designed the infinite scrolling for! Who knew it would become this mighty molten mess?! </br> <h6> #infinitescroll #invention #fail </h6> </h3> </br> </p> </center>',
  "<center> <img src='images/azaraskin.png'> <p> <h2> @AzaRaskinOG  </h2> </br> <br> <h3> Millions have been addicted to the scrolling mechanic…I am sorry I even invented this if you are reading this…</br> <h6> #sorry #guilty </h6> </h3> </br> </p> </center>",
  "<center> <img src='images/azaraskin.png'> <p> <h2> @AzaRaskinOG  </h2> </br> <br> <h3> Golly this feels aboslutely awful to see... </br> <h6> #science #computer #modern </h6> </h3> </br> </p> </center>",
  '<center> <img src="images/odddoc.png"> <p> <h2> @TheOddDoc </h2> </br> <br> <h3> Uh...if you are reading this...I suggest you do not constantly scroll...trust me... </br> <h6> #doctor #health #trustme </h6> </h3> </br> </p> </center>',
  "<center> <img src='images/odddoc.png'> <p> <h2> @TheOddDoc </h2> </br> <br> <h3> This manager has certainly ruined a lot of people's brains with this... </br> <h6> #managerhate #doctor </h6> </h3> </br> </p> </center>",
  "<center> <img src='images/odddoc.png'> <p> <h2> @TheOddDoc </h2> </br> <br> <h3> Wait! Have you heard the worldwide human being scrolls through social media for 2 hours and 31 minutes! Don't be that person, sir! </br> <h6> #careful #lookout #addiction </h6> </h3> </br> </p> </center>",
  '<center> <img src="images/odddoc.png"> <p> <h2> @TheOddDoc </h2> </br> <br> <video width="300" height="165" controls> <source src="videos/brainscroll.mp4" type="video/mp4"> </video> </br> </p> </center>',
]
  data[1] = [
    "Some random line that I don't know of",
    "I don't care what I'm writing here",
    "Site time!",
    "Only four in this array"  
]

  for(i=0; i<500;i++){
    data[1][i] = "random generated text"; 
  }